# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b57850184aabfdb391836ad7dbc2cdadc796d98d70191f3afb731747c7c1f6ee0fa60d9b138e3052d518358c58f52a0a69296a0b50d440e4d3c7832c28003d4f

test:
  secret_key_base: 6684e19835d54069383cf833bcf09cfb49a9f22cb334edf9641acfa407d9d70b31b1455660f81a10b4ec86cd2328ab374886bf5b82919d2ee7fa98d9fcc1ec6f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
